import reflex as rx


def hero() -> rx.Component:
    return rx.box(
        rx.box(
            rx.box(
                position="absolute",
                top="-12%",
                left="-8%",
                width="42%",
                height="52%",
                background="radial-gradient(circle, rgba(66, 131, 246, 0.24) 0%, rgba(66, 131, 246, 0) 72%)",
                filter="blur(2px)",
                pointer_events="none",
            ),
            rx.box(
                position="absolute",
                bottom="-20%",
                right="-10%",
                width="46%",
                height="56%",
                background="radial-gradient(circle, rgba(250, 164, 71, 0.2) 0%, rgba(250, 164, 71, 0) 72%)",
                filter="blur(2px)",
                pointer_events="none",
            ),
            rx.grid(
                rx.vstack(
                    rx.heading(
                        "Code review that is fast, clear, and reliable.",
                        size="7",
                        color="#f9fbff",
                        line_height="1.18",
                        letter_spacing="-0.02em",
                        max_width="520px",
                    ),
                    rx.text(
                        "Analyze multilingual code with static checks, external diagnostics, and AI insights without context switching.",
                        color="#c7d8ef",
                        font_size="1rem",
                        max_width="520px",
                        line_height="1.7",
                    ),
                    rx.hstack(
                        rx.link(
                            rx.button(
                                "Open Review Workspace",
                                color_scheme="orange",
                                variant="solid",
                                size="3",
                                border_radius="12px",
                                box_shadow="0 12px 26px rgba(240, 165, 62, 0.33)",
                                _hover={"transform": "translateY(-2px) scale(1.01)"},
                            ),
                            href="/posts",
                        ),
                        rx.link(
                            rx.button(
                                "Ask the Assistant",
                                variant="outline",
                                color_scheme="orange",
                                size="3",
                                border_radius="12px",
                                _hover={"background": "rgba(251, 191, 36, 0.12)"},
                            ),
                            href="/assistant",
                        ),
                        spacing="4",
                        flex_wrap="wrap",
                        width="100%",
                    ),
                    rx.text(
                        "Supports 8 languages with static and external diagnostics.",
                        color="#8fa7ca",
                        font_size="0.9rem",
                    ),
                    align="start",
                    spacing="6",
                    width="100%",
                ),
                rx.box(
                    rx.box(
                        rx.image(
                            src="/code-review-hero.svg",
                            alt="Code review illustration",
                            width="100%",
                            max_width="500px",
                            border_radius="20px",
                            box_shadow="0 26px 56px rgba(2, 8, 24, 0.48)",
                        ),
                        background="linear-gradient(140deg, rgba(41, 98, 188, 0.24) 0%, rgba(246, 172, 70, 0.1) 100%)",
                        border_radius="26px",
                        padding="0.92rem",
                        backdrop_filter="blur(8px)",
                        box_shadow="0 18px 44px rgba(2, 8, 24, 0.36)",
                        transition="transform 0.24s ease, box-shadow 0.24s ease",
                        _hover={
                            "transform": "translateY(-4px)",
                            "box_shadow": "0 24px 50px rgba(2, 8, 24, 0.44)",
                        },
                    ),
                    display="flex",
                    justify_content="center",
                    width="100%",
                ),
                columns={"base": "1", "lg": "2"},
                spacing="7",
                width="100%",
                align_items="center",
                padding={"base": "2.3rem", "md": "3.2rem", "lg": "4.2rem"},
            ),
            position="relative",
            overflow="hidden",
        ),
        width="100%",
        border="none",
        border_radius="26px",
        background="linear-gradient(155deg, rgba(8, 18, 39, 0.9) 0%, rgba(6, 15, 33, 0.94) 64%)",
        box_shadow="0 26px 70px rgba(1, 7, 20, 0.44)",
        backdrop_filter="blur(10px)",
    )
